# handlers file for first-role
---
  - name: restart apache
    become: yes
    service:
      name: apache2
    state: restarted

  - name: restart mysql
    become: yes
    service:
      name: mysql
    state: restarted