---
  - name: Set up Apache virtuahHost
    template:
      src: "files/apache2.conf.j2"
      dest: "/etc/apache2/sites-available/{{ app_url_conf }}"

  - name: Enable new site
    shell: /usr/sbin/a2ensite {{ app_url_conf }}
    notify: 
      - restart apache

  - name: Disable default Apache site
    shell: /usr/sbin/a2dissite 000-default.conf
    when: disable_default
    notify: 
      - restart apache

  - name: Default htaccess
    become: yes
    template: 
      src: "files/htaccess.j2"
      dest: "/var/www/html/wordpress"
      owner: "{{ app_user }}"
      group: "{{ app_user }}"
      mode: '0755'
    notify:
      - restart apache