---
  - name: install mysql-server
    become: yes
    apt: 
      name: mysql-server
      update_cache: yes
      state: latest
    notify:
      - restart mysql    

  - name: "Debian | Install Mysql Client package"
    apt:
      name: "{{ item }}"
      state: present   
    with_items:
      - mysql-client
      - python3-dev
      - libmysqlclient-dev
      - python3-mysqldb

  - name: changing root password
    become: yes
    template:
      src: "files/my.cnf.j2"
      dest: "/root/.my.cnf"
    notify:
      - restart mysql   

  - name: Changing native password
    command:  mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '"{{ mysql_password }}"';"

  - name: Adding MySQL DB
    mysql_db:
      name: "{{ wp_mysql_db }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present


#  - name: Configure my.cnf
#      copy: 
#       src: "./first-role/templates/my.cnf"
#       dest: "/etc/mysql/my.cnf"
#       owner: {{ app_user }}
#        group: {{ app_user }}
#        mode: '0755'
#    notify:
#      - restart mysql
  