---   
  - name: "Updating the repo"
    become: yes
    apt: 
      update_cache: yes

  - name: Add PHP 7 PPA repository
    become: yes
    apt:
      repo: 'ppa:ondrej/php'
        
  - name: Installation PHP 7.4
    become: yes
    apt: 
      name: php7.4 
      state: present
      update_cache: yes

  - name: install lamp stack
    become: yes
    apt:
      pkg:
        - php7.4-mysql
        - php7.4-curl
        - php7.4-json
        - php7.4-cgi
        - php7.4-xsl
        - php7.4-cgi
        - php7.4-gd
        - php7.4-mbstring
        - php7.4-zip
        - php7.4-xmlrpc
        - php7.4-soap
        - php7.4-intl
        - libapache2-mod-php
      state: present
      update_cache: yes