---
  - name: install phpmyadmin-server
    become: yes
    apt: 
      name: phpmyadmin
      update_cache: yes
      state: latest
    notify:
      - restart apache

  - name: adding phpmyadmin config file
    shell:
      echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf

    notify:
      - restart mysql
      - restart apache
