---
 - name: Install prerequisites
   apt: 
     name: aptitude 
     update_cache: yes
     state: latest 
     force_apt_get: yes
   tags: [ system ]
 
 - name: "Cloning & Unzipping wordpress"
   unarchive:
     src: https://wordpress.org/latest.tar.gz
     dest: /var/www/html
     remote_src: yes
   tags: [ wordpress ]

 - name: Set ownership
   file: path="/var/www/html" state=directory recurse=yes owner="{{ app_user }}" group="{{ app_user }}"
   tags: [ wordpress-permsission-grant ]

 - name: Copy sample config file
   command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php
   become: yes

 - name: Update WordPress config file
   become: yes
   template:
     src: "files/wp-config.j2"
     dest: "/var/www/html/wordpress/wp-config.php"
  

 