---
  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /home/test/Downloads/wordpress.tar.gz
    validate_certs: no

  - name: Extract WordPress
      unarchive: 
        src: /home/test/Downloads/wordpress.tar.gz 
        dest: /var/www/html/ 
    become: yes

  - name: Configure my.cnf
      copy: 
       src: "./first-role/files/wp-config.j2"
       dest: "/var/www/html/wordpress/wp-config"
       owner: {{ app_user }}
       group: {{ app_user }}
       mode: '0755'
